### ISSUE TITLE
thl vs subsample

### ISSUE THREAD

**Issue by ddrinan** [laurabenestan/Lobster-assigner#2]
Thanks so much for this informative tutorial. I just wanted to make sure I understand what the commands are doing.

When you set thl=0.5 and subsample=36, assigner randomly samples 36 individuals from each sample then splits it into a training dataset of 18 and a hold out data set of 18. Is that right?

**Comment by thierrygosselin** [comment]
That's right.
And to control iteration for these 2 arguments:
* `thl` iteration's are controlled with : `iteration.method`
* `subsample` iteration's are controlled with : `iteration.subsample`

The function changed substantially since the erratum, so make sure to read the argument and documentation for `assigner::assignment_ngs`.

**Comment by ddrinan** [comment]
Great, thanks.

**Comment by ddrinan** [comment]
Actually, one more question. If I set subsample=50, that occurs before the sample is partitioned into training data and hold out data correct?

**Comment by thierrygosselin** [comment]
yes

`subsample`:
(Integer or Proportion) Default is no subsampling, subsample = NULL. With a proportion argument subsample = 0.15, 15 percent of individuals in each populations are chosen randomly to represent the dataset. With subsample = 36, 36 individuals in each populations are chosen randomly to represent the dataset.

For each iteration a new set of (in your example) 50 individuals are randomly chosen to represent the dataset. All the other filters are donne after (e.g. monomorphic.out, common.markers, etc). THL and so on.

**Comment by thierrygosselin** [comment]
For question about assigner, move the discussion to the package GitHub page.
Cheers
